-- Deprecated: local Postgres init is now done by docker/postgres/init.sh
--
-- This file is intentionally kept credential-free. If you are looking for the
-- dev database/user bootstrap logic, see:
--   docker/postgres/init.sh
