package com.example.usbilling.hr.garnishment

import com.example.usbilling.shared.CustomerId
import com.example.usbilling.shared.UtilityId
import com.example.usbilling.shared.Money
import org.h2.jdbcx.JdbcDataSource
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.springframework.jdbc.core.JdbcTemplate
import java.time.LocalDate
import kotlin.test.assertEquals

class JdbcGarnishmentLedgerRepositoryTest {

    private lateinit var jdbcTemplate: JdbcTemplate
    private lateinit var repo: JdbcGarnishmentLedgerRepository

    private val employerId = UtilityId("EMP-GARN-LEDGER-TEST")
    private val employeeId = CustomerId("EE-GARN-LEDGER-TEST")

    @BeforeEach
    fun setUp() {
        val dataSource = JdbcDataSource().apply {
            setURL("jdbc:h2:mem:hr_garn_ledger;DB_CLOSE_DELAY=-1")
            user = "sa"
            password = ""
        }

        jdbcTemplate = JdbcTemplate(dataSource)
        repo = JdbcGarnishmentLedgerRepository(jdbcTemplate)

        jdbcTemplate.execute(
            """
            CREATE TABLE IF NOT EXISTS garnishment_ledger (
                employer_id           VARCHAR(64)  NOT NULL,
                employee_id           VARCHAR(64)  NOT NULL,
                order_id              VARCHAR(128) NOT NULL,
                total_withheld_cents  BIGINT       NOT NULL,
                initial_arrears_cents BIGINT           NULL,
                remaining_arrears_cents BIGINT         NULL,
                last_check_date       DATE             NULL,
                last_paycheck_id      VARCHAR(128)     NULL,
                last_pay_run_id       VARCHAR(128)     NULL,
                created_at            TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at            TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT pk_garnishment_ledger PRIMARY KEY (employer_id, employee_id, order_id)
            );
            """.trimIndent(),
        )

        jdbcTemplate.execute(
            """
            CREATE TABLE IF NOT EXISTS garnishment_withholding_event (
                id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                employer_id           VARCHAR(64)  NOT NULL,
                employee_id           VARCHAR(64)  NOT NULL,
                order_id              VARCHAR(128) NOT NULL,
                paycheck_id           VARCHAR(128) NOT NULL,
                pay_run_id            VARCHAR(128)     NULL,
                check_date            DATE         NOT NULL,
                withheld_cents        BIGINT       NOT NULL,
                net_pay_cents         BIGINT       NOT NULL,
                created_at            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT uq_garnishment_withholding_event UNIQUE (employer_id, employee_id, order_id, paycheck_id)
            );
            """.trimIndent(),
        )

        jdbcTemplate.update("DELETE FROM garnishment_withholding_event")
        jdbcTemplate.update("DELETE FROM garnishment_ledger")
    }

    @Test
    fun `recordWithholdings is idempotent and does not double-count ledger totals`() {
        val event = GarnishmentWithholdingEventView(
            orderId = "ORDER-1",
            paycheckId = "PAYCHECK-1",
            payRunId = "PAYRUN-1",
            checkDate = LocalDate.parse("2025-01-31"),
            withheld = Money(123_45L),
            netPay = Money(1000_00L),
        )

        // Send the same event twice.
        repo.recordWithholdings(employerId, employeeId, listOf(event, event))

        val ledger = repo.findByEmployee(employerId, employeeId)
        assertEquals(1, ledger.size)
        assertEquals(123_45L, ledger.getValue("ORDER-1").totalWithheld.amount)

        val eventCount = jdbcTemplate.queryForObject(
            "SELECT COUNT(*) FROM garnishment_withholding_event WHERE employer_id = ? AND employee_id = ? AND order_id = ? AND paycheck_id = ?",
            Long::class.java,
            employerId.value,
            employeeId.value,
            "ORDER-1",
            "PAYCHECK-1",
        )
        assertEquals(1L, eventCount)
    }
}
