-- Append-only audit trail for HR write operations.
--
-- Enterprise posture:
-- - Prefer append-only events over mutating history.
-- - Store correlation and principal identity when available.

CREATE TABLE IF NOT EXISTS hr_audit_event (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    employer_id              VARCHAR(64)  NOT NULL,

    entity_type              VARCHAR(64)  NOT NULL,
    entity_id                VARCHAR(128) NOT NULL,
    action                   VARCHAR(64)  NOT NULL,

    effective_from           DATE             NULL,

    correlation_id           VARCHAR(128)     NULL,
    principal_sub            VARCHAR(256)     NULL,
    principal_scope          VARCHAR(256)     NULL,
    idempotency_key          VARCHAR(256)     NULL,

    before_json              TEXT             NULL,
    after_json               TEXT             NULL,

    created_at               TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_hr_audit_event_entity
    ON hr_audit_event (employer_id, entity_type, entity_id, created_at);
