ALTER TABLE pay_run ADD COLUMN approval_status VARCHAR(32) NOT NULL DEFAULT 'PENDING';
ALTER TABLE pay_run ADD COLUMN approved_at TIMESTAMP;
ALTER TABLE pay_run ADD COLUMN payment_status VARCHAR(32) NOT NULL DEFAULT 'UNPAID';
ALTER TABLE pay_run ADD COLUMN paid_at TIMESTAMP;

ALTER TABLE paycheck ADD COLUMN approval_status VARCHAR(32) NOT NULL DEFAULT 'PENDING';
ALTER TABLE paycheck ADD COLUMN approved_at TIMESTAMP;
ALTER TABLE paycheck ADD COLUMN payment_status VARCHAR(32) NOT NULL DEFAULT 'UNPAID';
ALTER TABLE paycheck ADD COLUMN paid_at TIMESTAMP;
