-- HR schema: employees, employment_compensation, pay_period

CREATE TABLE IF NOT EXISTS employee (
    employer_id                  VARCHAR(64)  NOT NULL,
    employee_id                  VARCHAR(64)  NOT NULL,

    -- Core identification fields (names kept minimal for now)
    first_name                   VARCHAR(100)     NULL,
    last_name                    VARCHAR(100)     NULL,

    home_state                   CHAR(2)      NOT NULL,
    work_state                   CHAR(2)      NOT NULL,

    filing_status                VARCHAR(32)  NOT NULL,
    employment_type              VARCHAR(32)  NOT NULL DEFAULT 'REGULAR',

    hire_date                    DATE             NULL,
    termination_date             DATE             NULL,

    dependents                   INTEGER          NULL,

    federal_withholding_exempt   BOOLEAN      NOT NULL DEFAULT FALSE,
    is_nonresident_alien         BOOLEAN      NOT NULL DEFAULT FALSE,

    w4_annual_credit_cents       BIGINT           NULL,
    w4_other_income_cents        BIGINT           NULL,
    w4_deductions_cents          BIGINT           NULL,
    w4_step2_multiple_jobs       BOOLEAN      NOT NULL DEFAULT FALSE,

    additional_withholding_cents BIGINT           NULL,

    fica_exempt                  BOOLEAN      NOT NULL DEFAULT FALSE,
    flsa_enterprise_covered      BOOLEAN      NOT NULL DEFAULT TRUE,
    flsa_exempt_status           VARCHAR(32)  NOT NULL DEFAULT 'NON_EXEMPT',
    is_tipped_employee           BOOLEAN      NOT NULL DEFAULT FALSE,

    CONSTRAINT pk_employee PRIMARY KEY (employer_id, employee_id)
);

-- Effective-dated base compensation for employees
CREATE TABLE IF NOT EXISTS employment_compensation (
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employer_id                  VARCHAR(64)  NOT NULL,
    employee_id                  VARCHAR(64)  NOT NULL,

    effective_from               DATE         NOT NULL,
    effective_to                 DATE         NOT NULL,

    compensation_type            VARCHAR(16)  NOT NULL, -- 'SALARIED' or 'HOURLY'

    annual_salary_cents          BIGINT           NULL,
    hourly_rate_cents            BIGINT           NULL,
    pay_frequency                VARCHAR(32)  NOT NULL,

    CONSTRAINT fk_comp_employee FOREIGN KEY (employer_id, employee_id)
        REFERENCES employee (employer_id, employee_id)
);

CREATE INDEX IF NOT EXISTS idx_employment_comp_effective
    ON employment_compensation (employer_id, employee_id, effective_from, effective_to);

-- Pay periods for an employer
CREATE TABLE IF NOT EXISTS pay_period (
    employer_id      VARCHAR(64)  NOT NULL,
    id               VARCHAR(64)  NOT NULL,

    start_date       DATE         NOT NULL,
    end_date         DATE         NOT NULL,
    check_date       DATE         NOT NULL,

    frequency        VARCHAR(32)  NOT NULL,
    sequence_in_year INTEGER          NULL,

    CONSTRAINT pk_pay_period PRIMARY KEY (employer_id, id)
);

CREATE INDEX IF NOT EXISTS idx_pay_period_check_date
    ON pay_period (employer_id, check_date);