-- Garnishment arrears ledger and event history

CREATE TABLE IF NOT EXISTS garnishment_ledger (
    employer_id           VARCHAR(64)  NOT NULL,
    employee_id           VARCHAR(64)  NOT NULL,
    order_id              VARCHAR(128) NOT NULL,

    -- Aggregate totals for this order
    total_withheld_cents  BIGINT       NOT NULL,
    initial_arrears_cents BIGINT           NULL,
    remaining_arrears_cents BIGINT         NULL,

    last_check_date       DATE             NULL,
    last_paycheck_id      VARCHAR(128)     NULL,
    last_pay_run_id       VARCHAR(128)     NULL,

    created_at            TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_garnishment_ledger PRIMARY KEY (employer_id, employee_id, order_id)
);

CREATE INDEX IF NOT EXISTS idx_garnishment_ledger_employee
    ON garnishment_ledger (employer_id, employee_id);


CREATE TABLE IF NOT EXISTS garnishment_withholding_event (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    employer_id           VARCHAR(64)  NOT NULL,
    employee_id           VARCHAR(64)  NOT NULL,
    order_id              VARCHAR(128) NOT NULL,

    paycheck_id           VARCHAR(128) NOT NULL,
    pay_run_id            VARCHAR(128)     NULL,
    check_date            DATE         NOT NULL,

    withheld_cents        BIGINT       NOT NULL,
    net_pay_cents         BIGINT       NOT NULL,

    created_at            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_garnishment_withholding_event UNIQUE (employer_id, employee_id, order_id, paycheck_id)
);

CREATE INDEX IF NOT EXISTS idx_garnishment_event_employee
    ON garnishment_withholding_event (employer_id, employee_id, order_id);

CREATE INDEX IF NOT EXISTS idx_garnishment_event_check_date
    ON garnishment_withholding_event (check_date);
